name: CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{github.workspace}}/vcpkg

jobs:
  linux:
    name: Linux-x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
         
      - name: Install Qt
        run: |
            sudo apt-get update --fix-missing
            sudo apt install -y qtbase5-dev
          
      - uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{env.VCPKG_ROOT}}'
          runVcpkgInstall: false
          vcpkgJsonIgnores: "['**/vcpkg/**', '**/vcpkg_config/**']"
         
      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2
      
      - name: Prepare artifacts
        run: |
          mkdir "Half-Life Asset Manager"
          mv build/hlam "Half-Life Asset Manager"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x64
          path: "Half-Life Asset Manager"

  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_msvc2019'
          dir: '${{github.workspace}}/qt/'
      
      - uses: lukka/get-cmake@latest
      
      - name: Restore artifacts, setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{env.VCPKG_ROOT}}'
          runVcpkgInstall: false
          vcpkgJsonIgnores: "['**/vcpkg/**', '**/vcpkg_config/**']"
      
      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DQt5_DIR=${{env.Qt5_DIR}}
          -A Win32
      
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j2
      
      - name: Prepare artifacts
        run: |
          mkdir "Half-Life Asset Manager"
          mv build/HLAM.exe "Half-Life Asset Manager"
          mv build/OpenAL32.dll "Half-Life Asset Manager"
          mv build/Qt5Core.dll "Half-Life Asset Manager"
          mv build/Qt5Gui.dll "Half-Life Asset Manager"
          mv build/Qt5Network.dll "Half-Life Asset Manager"
          mv build/Qt5Widgets.dll "Half-Life Asset Manager"
          mv build/imageformats "Half-Life Asset Manager/imageformats"
          mv build/platforms "Half-Life Asset Manager/platforms"
          mv build/styles "Half-Life Asset Manager/styles"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Win32
          path: "Half-Life Asset Manager"
